services:
  app:
    image: mcr.microsoft.com/devcontainers/java:17
    volumes:
      - ../:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - db
  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: delivery_db
      MYSQL_USER: delivery_user
      MYSQL_PASSWORD: delivery_password
    ports:
      - "3306:3306"
